---
- name: Install Python-Docker on the host
  pip:
    name: docker

- name: Start bird-lg Frontend
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    name: lg_frontend
    container_name: lg_frontend
    container_image: xddxdd/bird-lg-go:latest
    container_host_network: yes  # simplest way to access the proxy for now
    container_env:
      BIRDLG_LISTEN: "127.0.0.1:5000"
      BIRDLG_SERVERS: "{{ 
          groups['bgp_servers'] 
        | map('multi_extract', hostvars, ['looking_glass_display_name', 'internal_ip'])
        | map('format', '{}<{}>')
        | join(',')         
      }}"
      BIRDLG_TITLE_BRAND: "PASTEN-NET Looking Glass"
      BIRDLG_NAVBAR_BRAND: "PASTEN-NET Looking Glass"
      BIRDLG_NET_SPECIFIC_MODE: "dn42"
      BIRDLG_PROTOCOL_FILTER: "bgp"
