---
- name: Harden OpenSSH Server Config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'

- name: Disable short moduli
  shell: "awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp && mv /etc/ssh/moduli.tmp /etc/ssh/moduli"

- name: Restart OpenSSH Server
  service:
    name: ssh
    state: restarted
