---
galaxy_info:
  name: docker_systemd_service
  author: Manuel Hutter
  description: Create Systemd services for docker containers.
  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial
        - yakkety
        - zesty

  galaxy_tags:
    - system
    - systemd
    - server
    - docker

dependencies: []
