---
- name: Install Python-Docker on the host
  pip:
    name: docker

- name: Start bird-lg Proxy
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    name: lg_proxy
    container_name: lg_proxy
    container_image: xddxdd/bird-lgproxy-go:latest
    container_host_network: yes  # needed to get accurate traceroute results, etc.
    container_volumes:
      - '/var/run/bird:/var/run/bird'
    container_env:
      BIRDLG_LISTEN: "{{ internal_ip }}:8000"
      ALLOWED_IPS: "{{ groups['looking_glass'] | map('extract', hostvars, 'internal_ip') | join(',') }}"
