---
- name: Install Packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - bind9
    - resolvconf

- name: Enable Services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - named
    - resolvconf

- name: Point DNS to local
  copy:
    src: resolvconf_head
    dest: /etc/resolvconf/resolv.conf.d/head

- name: Configure Bind9 Options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options

- name: Configure Bind9 DN42 Zone
  copy:
    src: named.conf.local
    dest: /etc/bind/

- name: Restart Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - named
    - resolvconf
