---
- name: Cleanup Wireguard
  import_role:
    name: cleanup_wireguard
  vars:
    wg_conf_list: "{{ clients.keys() | list }}"
    wg_prefix: "{{ wireguard_client_prefix }}"

- name: Generate Wireguard Configs
  template:
    src: wg_tunnel.conf.j2
    dest: "{{ wireguard_conf_dir }}/{{ wireguard_client_prefix }}{{ item.key }}.conf"
  with_dict: "{{ clients }}"
  when: "'wireguard_tunnel' in item.value.keys()"
  register: generated_wireguard_configs

- name: Reload Wireguard
  service:
    name: "wg-quick@{{ wireguard_client_prefix }}{{ item.item.key }}"
    state: reloaded
    enabled: yes
  with_items: "{{ generated_wireguard_configs.results }}"
  when: item.changed
