---
- name: Apt Update
  apt:
    update_cache: yes

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bird2
    - wireguard
    - moreutils
    - net-tools
    - python3-pip
    - exa
    - tree
    - ipcalc-ng

- name: Add ls=exa alias
  lineinfile:
    path: /root/.bash_aliases
    line: "alias ls=exa"
    regexp: "^alias ls=exa$"
    state: present
    insertafter: EOF
    create: yes
